<?php
echo '<br>______________________________pre_1____________<br>';
echo preg_replace('#a#', '!', 'aabbaa'); echo '<br>';
echo str_replace('a', '!', 'aabaa'); echo '<br>';
echo '<br>______________________________pre_2____________<br>';
echo preg_replace('#A#', '!', 'aAb').'<br>';
echo preg_replace('#A#i', '!', 'aAb').'<br>';
echo '<br>______________________________pre_3____________<br>';
echo preg_replace('#xax#', '!', 'xax xaax').'<br>';
echo preg_replace('#123#', '!', '123 xaax').'<br>';
echo preg_replace('#x3x#', '!', 'x3x xaax').'<br>';
echo preg_replace('#A3B#i', '!', 'a3b A3B').'<br>';
echo preg_replace('#x.x#', '!', 'xax xaax x&x x-x xaax').'<br>';
echo preg_replace('#x..x#', '!', 'xax xaax').'<br>';
echo '<br>______________________________pre_4____________<br>';
echo preg_replace('#xa+x#', '!', 'xx xax xaax xaaax xbx').'<br>';
echo preg_replace('#xa*x#', '!', 'xx xax xaax xaaax xbx').'<br>';
echo preg_replace('#xa?x#', '!', 'xx xax xaax xaaax xbx').'<br>';
echo '<br>______________________________pre_5____________<br>';
echo preg_replace('#x(ab)+x#', '!', 'xabx xababx xaabbx').'<br>';
echo '<br>______________________________pre_6____________<br>';
echo preg_replace('#a/+x#', '!', 'a+x ax aax aaax')."<br>";
echo '<br>______________________________pre_7____________<br>';
echo preg_replace('#a.+x#', '!', 'a23e4x qw x e').'<br>';
echo preg_replace('#a.+?x#', '!', 'a2a3e4x qw x e').'<br>';
echo '<br>______________________________ex_1_____________<br>';
echo preg_replace('#a.b#', 'FIND', 'ahb acb aeb aeeb adcb axeb');
echo '<br>______________________________ex_2_____________<br>';
echo preg_replace('#a..a#','FIND', 'aba aca aea abba adca abea');
echo '<br>______________________________ex_3_____________<br>';
echo preg_replace('#ab.a#','FIND', 'aba aca aea abba adca abea');
echo '<br>______________________________ex_4_____________<br>';
echo preg_replace('#ab+a#', 'FIND', 'aa aba abba abbba abca abea');
echo '<br>______________________________ex_5_____________<br>';
echo preg_replace('#ab*a#', 'FIND', 'aa aba abba abbba abca abea');
echo '<br>______________________________ex_6_____________<br>';
echo preg_replace('#ab?a#', 'FIND', 'aa aba abba abbba abca abea');
echo '<br>______________________________ex_7_____________<br>';
echo preg_replace('#(ab)+#', 'FIND', 'ab abab abab abababab abea');
echo '<br>______________________________ex_8_____________<br>';
echo preg_replace('#a\.a#', 'FIND', 'a.a aba aea');
echo '<br>______________________________ex_9_____________<br>';
echo preg_replace('#2\+3#','FIND','2+3 223 2223');
echo '<br>______________________________ex_10_____________<br>';
echo preg_replace('#2\++3#', 'FIND', '23 2+3 2++3 2+++3 345 567');
echo '<br>______________________________ex_11_____________<br>';
echo preg_replace('#2\+*3#','FIND', '23 2+3 2++3 2+++3 445 677');
echo '<br>______________________________ex_12_____________<br>';
echo preg_replace('#\*q+\+#', 'FIND', '*+ *q+ *qq+ *qqq+ *qqq qqq+'); 
echo '<br>______________________________ex_13_____________<br>';
echo preg_replace('#\*q*\+#', 'FIND', '*+ *q+ *qq+ *qqq+ *qqq qqq+'); 
echo '<br>______________________________ex_14_____________<br>';
echo preg_replace('#a.*?a#', '!', 'aba accca azzza wwwwa');
echo '<br>________________________________________________<br>';
?>
// s/1/\=line('.')
